Estilos pagina de autenticacion movil
GammaFec/Gamma pull request #55
Opened 2021-03-31 18:11 UTC by Ignaherrero

# Estilos autenticacion movil

![image](https://user-images.githubusercontent.com/44342115/113190821-295ed400-9233-11eb-86d1-1baf7bc8b969.png)
![image](https://user-images.githubusercontent.com/44342115/113190845-3085e200-9233-11eb-8cdf-2e6d03382e3c.png)

2021-04-04 21:24 UTC, anaggithub commented on pull request.txt
> +# componente o página
Ke es este machetito? super cute ^^

2021-04-05 00:16 UTC, Ignaherrero commented on pull request.txt
> +# componente o página
Jajajajajaja el otro día lo andaba buscando y no lo encontré, dije "bue anda a saber dónde quedó" cuando vi tu comentario me hiciste acordar jaja al final acá estaba jajajaja

2021-04-11 23:37 UTC, nykka requested changes
Está genial! Sólo te dejé unos comentarios sobre los `<br/>` y los `transform` que me parece que hay que eliminarlos. Si queres lo discutimos en el canal.

2021-04-11 23:37 UTC, nykka commented on src/pages/MovilAuth/RequestNumber/index.tsx
> +                Ingresa tu <br /> número de telefono
Tratemos de no usar `<br/>`, no es bueno para la accesibilidad. Si tiene que quedar en dos lineas, quizás sea mejor agregar un padding a los lados.

2021-04-11 23:37 UTC, nykka commented on src/pages/MovilAuth/ValidateNumber/styles.ts
> +    transform: translate(1px, 4px);
Esto es raro. Porque lo tuviste que usar?

2021-04-11 23:37 UTC, nykka commented on src/pages/MovilAuth/ValidateNumber/styles.ts
> +    transform: translateY(-1px);
Todos estos transform me resultan raros. Son realmente necesarios?

2021-04-23 15:11 UTC, Ignaherrero commented on src/pages/MovilAuth/RequestNumber/index.tsx
> +                Ingresa tu <br /> número de telefono
Intente usar los padding como me recomendaste pero se me complico, use span y en los estilos le puse display block, Intente bastante con el padding pero lo que me paso es que el texto de arriba era muy chiquito y el texto de abajo mucho más grande

2021-05-14 01:41 UTC, 9gustin commented
Tiene conflictous 👀

2021-05-27 00:20 UTC, anaggithub commented on src/components/Button/types.ts
> +    onClick?: React.MouseEventHandler<HTMLButtonElement>;
onClick y handleClick no son lo mismo??

2021-05-27 00:22 UTC, anaggithub commented on src/components/Button/types.ts
> +    onClick?: React.MouseEventHandler<HTMLButtonElement>;
Holi! onClick y handleClick no serían lo mismo?? O cuál sería la diferencia... no me doy cuentaa

2021-05-27 00:22 UTC, anaggithub commented on src/components/Header/styles.ts
>      display: flex;
Acá por qué fletaste el height: 10vh? Imagino que por algo lohabía puesto el agus.. no se romperá otra pagina donde lo estan usando? O era acá donde lo estaban usando nomás.. jejejeje Pregunto x las dudas

2021-05-27 00:25 UTC, anaggithub commented on src/pages/MovilAuth/RequestNumber/index.tsx
> +                Ingresa tu <br /> número de telefono
Y si usamos <span>? Así siempre se van a mantener en líneas separadas cada frase. Onda:
<span>Ingresa tu </span>
<span> blabla </span>

2021-06-07 17:16 UTC, Ignaherrero commented on src/components/Button/types.ts
> +    onClick?: React.MouseEventHandler<HTMLButtonElement>;
Tenes razon Hadita, no se porque lo agregue o que se me cruzo por la cabeza fue cuando di mis primeros pasos con typescript y tenia una ensalada terrible en la capocha jajajaja

2021-06-07 17:33 UTC, Ignaherrero commented on src/components/Header/styles.ts
>      display: flex;
Uuyy gracias Hadita, crei haber modificado un componente dentro de movilauth pero me fui a otro componente, lo que hice ahora fue comentar un botón que todavía no esta en figma (dentro de movilauth), cuando este lo puedo descomentar y agregar los estilos para que quede pipicucu xD

2021-06-12 00:41 UTC, anaggithub commented on src/pages/MovilAuth/ValidateNumber/index.tsx
> +    // const submit = (): void => handleSubmit(code);
Holi! Recién veo que habías dejado una aclaración con respecto a esta línea comentada. 
En realidad este ticket es solo sobre estilos. Lo que son los submits o un handle submit eso ya es lógica y funcionalidad de la página, lo cual este ticket no incluye. 

No sé si este comentario venía de antes o por qué está ahí, pero lo que yo haría es no agregar ningun handle, que lo agregue luego quien trabaje en ello. Tratemos de distinguir bien lo que incluye cada uno delos tickets y lo que no incluye. Este es solo de agregar estilos. No sé si se entiende la idea? :D

2021-06-12 00:43 UTC, anaggithub commented on public/index.html
> +</html>
Estos cambios en este index por qué los estás mandando? Es parte del ticket? Me asusta que mandes esto y se rompa el formato en el proyecto y luego ocurra lo de siempre, que develop deja de correr y tira error. En este momento develop está bien y este archivo no tira errores entonces por eso me da dudas.

Fijate de actualizar esta rama con develop, porque muy posiblemente te quedó desactualizada!!

2021-06-21 18:20 UTC, nykka approved these changes

2021-06-21 18:22 UTC, anaggithub requested changes

2021-06-21 18:22 UTC, anaggithub commented on src/pages/MovilAuth/RequestNumber/styles.ts
> +export const StyledButtonContinue = styled(StyledButton)`
REcién veo esto!! No lo había visto antes... ¿por qué estás importando los styles del button? Tenés que importar el componente entero! Me atrevo a decir que esto es mala práctica... La idea de reutilizar un componente es rehutilizar el componente entero, no sus estilos... No recuerdo si en el resto del proyecto lo han estado haciendo así pero si es el caso creo que está re mal! 

El componente button tiene una prop styles, y es ahí donde le tenés que pasar los estilos particulares para sobreescribir alguna cosa de sus estilos generales que no te sirvan para esta instancia en particular de esta page.. 

![image](https://user-images.githubusercontent.com/47753872/122809410-76879a80-d2a4-11eb-87b4-6494c243701b.png)

2021-06-21 19:08 UTC, Ignaherrero commented on src/pages/MovilAuth/RequestNumber/styles.ts
> +export const StyledButtonContinue = styled(StyledButton)`
Ahhh claa bueno lo corrijo , después quedo largo porque este ticket es de poner estilos a toda la librería por lo que tiene varios componentes y hay que agregar a cada uno de ellos , se fue largo pero es así

2021-06-23 15:28 UTC, anaggithub commented on src/pages/MovilAuth/RequestNumber/styles.ts
> +export const StyledButtonContinue = styled(StyledButton)`
No, de nada!!
Pero sí en este caso podríamos haber creado distintos PR para cada cosita de la page, si es que cada una era todo un tema por el hecho de usar la otra libreria. Entonces eso facilitaría las cosas a la hora de hacer el review después :D

2021-06-23 15:30 UTC, anaggithub commented on src/pages/MovilAuth/RequestNumber/styles.ts
> +export const StyledButtonContinue = styled(StyledButton)`
Ha, con el último marge dela funcionalidad de register creo que te sale un conflicto ahora. Me parece que es nomás el import en la page movil-auth, que yo lo actualicé. Calculo q es ese cambio nomás y ya.

2021-07-10 01:06 UTC, merged