Feature/funcionalidad pantalla login inputs
GammaFec/Gamma pull request #58
Opened 2021-05-05 15:20 UTC by Ignaherrero

# Agrego funcionalidad pantalla login

Agrego a la pantalla de Login la funcionalidad de mostrar y ocultar la contraseña
Agrego el autocompletado 

Tengo dudas sobre el uso de un png en la imagen, porque me acuerdo que quedamos en usar svg pero el componente estaba listo para usarse con imagen, ustedes me dicen si lo cambio y lo adapto para usarlo con svg

La pantalla de register no esta lista aun

![pantalla login funcionalidad](https://user-images.githubusercontent.com/44342115/117165754-27d97c00-ad9c-11eb-8192-6eb533642b8a.gif)
![image](https://user-images.githubusercontent.com/44342115/117162648-573ab980-ad99-11eb-971d-d46fc5a77d6f.png)

ticket: https://trello.com/c/6aupROKa/70-agregar-funcionalidades-para-el-input-del-password-en-las-pantallas-login-y-register

2021-05-12 18:54 UTC, AnibalDBXD reviewed
Un par de detalles

2021-05-12 18:54 UTC, AnibalDBXD commented on src/components/Input/index.tsx
> +/* eslint-disable jsx-a11y/no-autofocus */
Creo que estos comentarios los podrias quitar ¿?

2021-05-12 18:54 UTC, AnibalDBXD commented on src/components/Input/index.tsx
> +                // autoComplete={isLogin ? "current-password" : "new-password"}
Igual este jeje

2021-05-18 02:33 UTC, anaggithub requested changes

2021-05-18 02:33 UTC, anaggithub commented on src/components/Input/index.tsx
> +    const [inputShow, setPasswordVisibility] = useState(isText);
Estoy un poco confundida con lo que estás haciendo acá... generalmente los states se plantean de la siguiente forma: una variable, y un set para modificar esa misma variable. Entonces sería 
const [inputShow, setinputShow] = useState(isText);
o...
const [passwordVisibility, setPasswordVisibility] = useState(isText);
No sé si me explico?

2021-05-18 02:36 UTC, anaggithub commented
Con respecto a las imágenes svg, creo que sí la idea es usar svg, pero si en los diseños los íconos están en png no queda otra que usar png hasta que sebas nos haga los svg :D

2021-05-18 02:48 UTC, Ignaherrero commented on src/components/Input/index.tsx
> +    const [inputShow, setPasswordVisibility] = useState(isText);
Sisi te entiendo, mañana lo corrijo ^^

2021-05-18 03:01 UTC, Ignaherrero commented
> Con respecto a las imágenes svg, creo que sí la idea es usar svg, pero si en los diseños los íconos están en png no queda otra que usar png hasta que sebas nos haga los svg :D

Okaaaa, una pregunta si yo exporto como svg las ilustraciones que subió sebas, no son svg en realidad no?

2021-05-18 14:30 UTC, Ignaherrero commented on src/components/Input/index.tsx
> +/* eslint-disable jsx-a11y/no-autofocus */
Ahora que lo veo en el vscode, lo agrege porque sino eslint me da error, se puede deshabilitar esa regla ? aca en el código lo uso para que haga auto focus

2021-05-18 18:32 UTC, AnibalDBXD approved these changes

2021-05-19 21:17 UTC, 9gustin approved these changes

2021-05-19 22:49 UTC, merged