Arreglo husky
GammaFec/Gamma pull request #66
Opened 2021-05-21 21:54 UTC by Ignaherrero

# Husky

Hice las pruebas con windows y funciono, si puede pruebenlo en sus compus y me avisan si salio todo ok
Estoy usando npm, AGShorsh encontro en stackoverflow que husky esta andando mal con yarn, por eso corro los comandos con npm en el package.json

ticket: https://trello.com/c/0puQNJIy/79-investigar-porque-esta-fallando-husky-front

2021-05-22 01:06 UTC, 9gustin commented on package.json
> +        "src/**/*.{js,jsx,tsx}": [
aca ni falta .ts?

2021-05-22 01:56 UTC, Ignaherrero commented on package.json
> +        "src/**/*.{js,jsx,tsx}": [
cuando lo probe me corrigio tambien los archivos con extensión .ts, pero por las dudas lo voy a agregar

2021-05-22 17:17 UTC, 9gustin commented on package.json
> +        "src/**/*.{js,jsx,tsx}": [
ahhh de una

2021-05-22 17:17 UTC, 9gustin submitted a review, later dismissed

2021-06-19 17:52 UTC, AnibalDBXD approved these changes

2021-06-21 18:18 UTC, nykka requested changes
Se ve genial 👯 . Te deje un comentario sobre archivos que parece que no son parte del PR

2021-06-21 18:18 UTC, nykka commented on src/pages/MovilAuth/index.tsx
> +    const [veriResult, setVeriResult] = useState<firebase.auth.ConfirmationResult | null>();
Parece que esto no parte del PR para arreglar Husky. Podrías ponerlo en un PR separado?

2021-06-22 20:42 UTC, AnibalDBXD approved these changes

2021-07-03 22:28 UTC, anaggithub approved these changes

2021-07-03 22:34 UTC, anaggithub commented on src/pages/MovilAuth/index.tsx
> +    const [veriResult, setVeriResult] = useState<firebase.auth.ConfirmationResult | null>();
Es un fix para que compile Netlify! Se habló en otro PR y de hecho ya fue mergeado a develop ese cambio, solo que esta rama está desactualizada jaja

2021-07-07 22:44 UTC, merged