Feature/input update
GammaFec/Gamma pull request #72
Opened 2021-06-18 03:25 UTC by aledeloss

Hola! Ahí va el input con la prop iconPosition, que admite los valores 'left', 'right' o nada si no hay ícono. Lo ubiqué cambiando la flex-direction. Me parece que quedó bien, pero leo sus comentarios! También le cambié el position porque como estaba se superponía con el value del input :).

2021-06-18 16:15 UTC, AnibalDBXD reviewed
El archivo copy.txt no creo que deberia estar 🤔

2021-06-18 17:39 UTC, aledeloss commented
Cierto! Ahí lo corregí :)

2021-06-18 18:10 UTC, AnibalDBXD reviewed
Un par de cosas pero por lo demas bien!

2021-06-18 18:10 UTC, AnibalDBXD commented on src/components/Input/index.tsx
> +    iconPosition,
Esta prop puede ser llama iconPositionLeft o isIconLeft y cambiarlo a boolean ya que en lo estilos solo le evalua si el string es left

2021-06-18 18:10 UTC, AnibalDBXD commented on src/components/Input/index.tsx
> +        <StyledInputContainer iconPosition={iconPosition !== undefined ? iconPosition : "right"}>
con el cambio de arriba seria asi la condicional 
`
<StyledInputContainer iconPositionLeft={iconPositionLeft !== undefined && iconPositionLeft}>
`

2021-06-18 18:10 UTC, AnibalDBXD commented on src/components/Input/styles.tsx
> +export const StyledInputContainer = styled.div<{ iconPosition: string }>`
aca pasaria en vez de ser string un boolean

2021-06-18 18:10 UTC, AnibalDBXD commented on src/components/Input/styles.tsx
> +    flex-direction: ${(props): string => (props.iconPosition === "left" ? "row" : "row-reverse")};
y aca la condicinal cambiaria a: 
`
flex-direction: ${(props): string => (props.iconPositionLeft ? "row" : "row-reverse")};
`

2021-06-18 18:10 UTC, AnibalDBXD commented on src/components/Input/types.ts
> +    iconPosition?: string;
Y esto en vez de un string seria un `boolean` de todos modos si por cualquier razon tiene ser un string el iconPosition puedes poner ` iconPosition?: "left" | "right"` y se sabria que string exactamente recibiria

2021-06-19 00:55 UTC, aledeloss commented
Hecho!! Originalmente lo había hecho como boolean, tal como comentás. Y luego lo pasé a string porque me pareció que era mejor no ponerle una posición por defecto (pero se la puse igual. Así que ahí volví al boolean con iconPositionLeft.

2021-06-19 01:51 UTC, AnibalDBXD submitted a review, later dismissed
Ya no le veo mas peros 😊

2021-06-21 18:09 UTC, nykka commented on src/components/Input/index.tsx
> +            iconPositionLeft={iconPositionLeft !== undefined ? iconPositionLeft : false}>
No estoy muy segura de eso. Porque no pasar el valor de `iconPositionLeft` directamente y hacer el conditional rendering en el styled component?

2021-06-21 18:22 UTC, aledeloss commented on src/components/Input/index.tsx
> +            iconPositionLeft={iconPositionLeft !== undefined ? iconPositionLeft : false}>
Hola! Bueno, a mí intuitivamente me salió poner el condicional en el renderizado como decía. Pero como la tarea decía explícitamente hacerlo en el css pensé que era una decisón del proyecto. Ya lo pasé al css, pero puedo volver a cambiarlo si les parece mejor. Espero vuestros comentarios :)

2021-06-21 18:34 UTC, anaggithub requested changes
Holi! Me gusta cómo lo resolviste tan simple, bah al menos pude entender rápido lo que quisiste hacer y eso es todo un logro!! :D 

Lo que si, faltarían capturas de cómo queda!! Si el cambio que hiciste permite tener 3 opciones de input (icono a la derecha, icono a la izquierda, sin icono), lo ideal seria que en la descripcion del PR nos muestres una captura de cómo se verían estas tres opciones! Podés probarlas en alguna de las pages que ya existe y simplemente sacar la captura para mostrarnos, sin comitear nada de eso obvio :D

2021-06-22 02:21 UTC, aledeloss commented
Buenas! Aquí les comparto la imagen del login con los dos campos de siempre, más el de buscar: con ícono a la izquierda, a la derecha y sin ícono. Al componente input le agregué las props iconPositionLeft y onIconClick, para poder darle una acción al click. Por lo tanto también tuve que modificar el login, ya que ahora la función toggleVisibility del ojito también pasa por prop. Lo del condicional le dejé como estaba, en el css. Me parece que la salida de row/row-reverse simplifica bastante el tema, pero puedo volverlo a index.ts si les parece mejor.
Y por último, también corregí el typo que decía vadidInput en lugar de validInput. Nuevamente, espero sus comentarios :)

![imagen](https://user-images.githubusercontent.com/28830397/122852153-8922c380-d2e6-11eb-8799-da9a14ef4298.png)

2021-06-22 13:55 UTC, nykka approved these changes
🎉  Approved!!!

2021-06-22 20:41 UTC, AnibalDBXD approved these changes

2021-06-23 15:04 UTC, anaggithub approved these changes

2021-06-23 15:04 UTC, anaggithub commented
Triple approved! @

2021-06-24 18:48 UTC, merged